# Generated by Django 5.1.1 on 2024-10-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Civilites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('is_alive', models.BooleanField(default=True)),
                ('birthday', models.DateField()),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.civilites')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=100)),
                ('web_site', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('year_of_publication', models.DateField()),
                ('isbn', models.IntegerField(max_length=13)),
                ('summary', models.TextField()),
                ('price', models.CharField(max_length=15)),
                ('picture', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.authors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editors')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formats')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.languages')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.states')),
            ],
        ),
    ]
