# Generated by Django 5.0.2 on 2024-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
