# Generated by Django 5.0.2 on 2024-11-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_books_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.books"
            ),
        ),
    ]
