# Generated by Django 5.0.2 on 2024-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_returnhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnhistory",
            name="return_processed",
            field=models.BooleanField(default=False),
        ),
    ]
