# Generated by Django 5.0.2 on 2024-11-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_loan_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnhistory",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.books"
            ),
        ),
    ]
