# Generated by Django 5.0.2 on 2024-11-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_returnhistory_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="return_processed",
        ),
    ]
