# Generated by Django 5.0.2 on 2024-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_returnhistory_return_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnhistory",
            name="return_processed",
        ),
        migrations.AddField(
            model_name="loan",
            name="return_processed",
            field=models.BooleanField(default=False),
        ),
    ]
