# Generated by Django 5.0.2 on 2024-11-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_loan_return_processed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReturnHistory",
        ),
    ]
