# Generated by Django 5.0.2 on 2024-12-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_returnhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
